server:
  port: 8081

spring:
  sql:
    init:
      platform: postgres
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/libraryservicedb
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/dbchangelog.sql
    enabled: true
    url: jdbc:postgresql://localhost:5432/libraryservicedb
    user: postgres
    password: root
springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /openapi/swagger-ui.html
  api-docs:
    path: /openapi/api-docs
