server:
  port: 8082

spring:
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/userservicedb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/dbchangelog.sql
    enabled: true